---
- name: Install required system packages
  apt:
    pkg:
      - openjdk-11-jre
      - wget
      - vim
      - curl
  tags:
    - install
  
- name: Check existence of local env file
  local_action: stat path="{{ clojure_uberjar_webapp_app_env_local_path }}"
  register: app_env_local_file
  ignore_errors: True
  become: False
  tags:
    - configure

- name: Copy app env file
  template: src="{{ clojure_uberjar_webapp_app_env_local_path }}" dest="{{ clojure_uberjar_webapp_app_env_path }}"
  tags:
    - configure
  when: app_env_local_file.stat.exists
    
- name: Upload http env var file
  template: src="templates/http-env.j2" dest="{{ clojure_uberjar_webapp_app_http_env_path }}"
  tags:
    - configure

- name: Upload start script
  template: src="templates/start-app.sh.j2" dest="{{ clojure_uberjar_start_script_path }}" mode=755
  tags:
    - configure
    
- name: Upload web app systemd config file
  template: src="templates/app.service.j2" dest="/etc/systemd/system/{{ clojure_uberjar_webapp_app_service_name }}.service"
  tags:
    - configure

- name: Make app log directory
  file: state=directory path={{ clojure_uberjar_webapp_app_log_dir }} owner={{ clojure_uberjar_webapp_app_user }} group={{ clojure_uberjar_webapp_app_user }} mode=755
  tags:
    - install

  # A non-ansible script creates files/app.jar
- name: Copy uberjar
  copy: src=files/app.jar dest={{ clojure_uberjar_webapp_app_root }}/{{ clojure_uberjar_webapp_app_jar_name }}
  tags:
    - deploy

- name: Copy check script
  template: src="{{ clojure_uberjar_webapp_app_check_local_path }}" dest="{{ clojure_uberjar_webapp_app_root }}/check.sh" mode=755
  tags:
    - deploy
    - check

- name: combine configs
  assemble:
    src: "{{ clojure_uberjar_webapp_app_config_dir }}"
    dest: "{{ clojure_uberjar_webapp_app_combined_config_path }}"
    delimiter: "\n"
  tags:
    - deploy
    
- name: Run check
  command: chdir={{ clojure_uberjar_webapp_app_root }}/ bash ./check.sh
  when: clojure_uberjar_webapp_app_perform_check|bool
  tags:
    - deploy
    - check

- name: Confirm ok
  command: echo "restart this baby"
  tags:
    - deploy
  notify:
    - restart web app

- name: Notify install schemas
  command: echo "install me some schemas"
  tags:
    - deploy
  notify:
    - install schemas
  when: datomic_db_name is defined

- name: Enable app systemd
  systemd:
    name: "{{ clojure_uberjar_webapp_app_service_name }}"
    enabled: yes
  become: yes
  become_method: sudo
  tags:
    - install
